name: jhslack
favicon: null
layout_spectrum: 0.45826
typography_spectrum: 0.6406064229086041
title: Jackson Hole's Slack Community
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#482e25'
    - '#cb7d02'
    - '#827068'
    - '#e0b570'
  brandStrength: 0.041069233790040016
  lightness: 0.5133184588048607
  saturation: 0.912420597160235
  rhythmicContrast: 0.9755652211606503
purpose: []
